version: "3.7"

services:
  tf:
    network_mode: host
    image: hashicorp/terraform:1.1.3
    environment:
      TF_IN_AUTOMATION: ${TF_IN_AUTOMATION}
      TF_VAR_google_creds_path: "/root/.config/gcloud/application_default_credentials.json"
      TF_VAR_gcs_keys_bucket:
      TF_VAR_gcs_keys_bucket_eu:
      TF_VAR_cluster_project:
      TF_STATE_BUCKET:
      TF_STATE_PREFIX:
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
      - .:/workspace
      - /root/.kube
    logging:
      driver: "json-file"
    working_dir: /workspace
    entrypoint: "/bin/sh -c"
    command: "make plan"
